//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivrariaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class livro_autor
    {
        public int livro_codL { get; set; }
        public int autor_coda { get; set; }
    }
}
