//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivrariaDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LivrariaDBEntities : DbContext
    {
        public LivrariaDBEntities()
            : base("name=LivrariaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<assunto> assuntoes { get; set; }
        public virtual DbSet<autor> autors { get; set; }
        public virtual DbSet<Livro> Livroes { get; set; }
        public virtual DbSet<livro_assunto> livro_assunto { get; set; }
        public virtual DbSet<livro_autor> livro_autor { get; set; }
        public virtual DbSet<Vw_Livros> Vw_Livros { get; set; }
    }
}
