//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivrariaDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Livros
    {
        public int codL { get; set; }
        public string titulo { get; set; }
        public string editora { get; set; }
        public Nullable<int> edicao { get; set; }
        public string anopublicao { get; set; }
        public Nullable<decimal> preco { get; set; }
        public Nullable<int> livro_codl { get; set; }
        public Nullable<int> assunto_codAS { get; set; }
        public int id { get; set; }
        public int codAS { get; set; }
        public string descricao { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> autor_coda { get; set; }
        public int Expr2 { get; set; }
        public int codA { get; set; }
        public string nome { get; set; }
    }
}
