USE [master]
GO

/****** Object:  Database [LivrariaDB]    Script Date: 16/08/2020 14:01:14 ******/
CREATE DATABASE [LivrariaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LivrariaDB', FILENAME = N'D:\Database\LivrariaDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LivrariaDB_log', FILENAME = N'D:\Database\LivrariaDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LivrariaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LivrariaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LivrariaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LivrariaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LivrariaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LivrariaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LivrariaDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [LivrariaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LivrariaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LivrariaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LivrariaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LivrariaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LivrariaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LivrariaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LivrariaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LivrariaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LivrariaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LivrariaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LivrariaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LivrariaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LivrariaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LivrariaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LivrariaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LivrariaDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LivrariaDB] SET  MULTI_USER 
GO

ALTER DATABASE [LivrariaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LivrariaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LivrariaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LivrariaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LivrariaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LivrariaDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LivrariaDB] SET  READ_WRITE 
GO


